version: 2
updates:
  - package-ecosystem: "npm"
    open-pull-requests-limit: 1
    directory: "/"
    schedule:
      interval: "quarterly"
      day: "friday"
    reviewers:
      - "rusikf"
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 1
    directory: "/"
    schedule:
      interval: "quarterly"
      day: "friday"
    reviewers:
      - "rusikf"
